### ISSUE TITLE
Remove background-position: fixed from startpage on small screens

### ISSUE THREAD

**Issue by seanysean** [seanysean/learnchess-old#106]

**Comment by gtkpr** [comment]
hey, i can do this for you, but i'm new to contributing. in fact, this would be my first ever pull request. i've downloaded your project, but as of right now index.html, puzzledatabase.html, and puzzleschecklist.html seem to be pretty bare. did i download the right project? can you point me in the right direction? thanks<3 and please let me know if you would like me to do this for you!

**Comment by seanysean** [comment]
@gtkpr My apologies, I didn't notice this message until now. Unfortunately learnchess is not open source right now. Perhaps in the future...
