### ISSUE TITLE
Is there a way for me to help you with the coding proccess?

### ISSUE THREAD

**Issue by TheMouth888** [seanysean/learnchess-old#89]

**Comment by TheMouth888** [comment]
also are you on board with the compilation idea? i think u and i really cant do much by ourselves

**Comment by seanysean** [comment]
I am not sure, what languages can you code in?

**Comment by TheMouth888** [comment]
idk, i'll be working on my code skillz.

**Comment by seanysean** [comment]
Do you have any links to what you have coded?

**Comment by TheMouth888** [comment]
sorry,i don't i will work on it friend!

**Comment by seanysean** [comment]
Better LearnChess: https://github.com/seanysean/learnchess
